### ISSUE TITLE
new error!

### ISSUE THREAD

**Issue by Phoenix1112** [cosmiclearn/improve-content#4]
hello. thanks for nice tutorial.. But this code not working

package clearn
import "fmt"
func main()
{
	planetName := "Earth"
	numberOfMoons := 1
	fmt.Println(planetName, numberOfMoons)
}

go run: cannot run non-main package

https://www.cosmiclearn.com/go/variables.php

I'm gonna ask you for something...I translate the page into Turkish . because i dont know english...
sample codes are not translated into Turkish. ..This is a very nice feature ..but the output of sample code is translated into Turkish..please don't let the printout of the codes be detected by any google translate..
all the examples and outputs that you show should appear in Eng...
only the text you type should be detected by google translate...

example :+1:   when I translate the page into Turkish, the output of the sample code is complex

![ekran goruntusu_2019-02-05_00-14-08](https://user-images.githubusercontent.com/42475284/52237593-077b9800-28db-11e9-8d1f-fd5ab6945715.png)

I'm turning the page back to English so I can see the output ..the above output does not make any sense in Turkish..because the output seems mixed

**Comment by cosmiclearn** [comment]
Hi CyberTheReape,

Thank you for going through the tutorial. I have fixed the code in the Go variables page as shown below.

Please revisit the page after refreshing the cache:
https://www.cosmiclearn.com/go/variables.php

package main
import "fmt"

func main() {
    planetName := "Earth"
    numberOfMoons := 1
    fmt.Println(planetName, numberOfMoons)
}

I will look into how to avoid translating the output.

Regards,
CosmicLearn

**Comment by CyberTheReape** [comment]
Thank you for your interest. cosmiclearn is my favorite web site.. very recently I will share your site on turkish forums. There are no sources in Turkish that provide training for golang software language.. so we are researching English sources..by turning the page in Turkish, we are trying to understand the lessons. We thank you for everything...

**Comment by cosmiclearn** [comment]
Hi Phoenix1112

We have now published a dedicated tutorial for Golang in Turkish language. The outputs now appear in English.
URL: https://www.cosmiclearn.com/lang-tr/go-index.php

We thank you for continued support of cosmiclearn project.

**Comment by Phoenix1112** [comment]
very beautiful... thank you so much... I'm going to give this information to everyone...
really appreciate you.

**Comment by Phoenix1112** [comment]
90% properly written in turkish.. some words are misspelled. I am preparing an arrangement for you.  after a few days I can correct the mistakes written in all courses... I'm correcting the misspelled places in lesson 2 now...after a few days I will correct all.
