### ISSUE TITLE
TypeScript Variables

### ISSUE THREAD

**Issue by Coregenious** [cosmiclearn/improve-content#5]
I want to thank you very much for the simple and easy to understand tutorials you put on your website. I am enjoying learning about them and will continue to do so again and again. I was going through your tutorial on TypeScript Variables and discovered an error. You said that a variable can be assigned [the value of] any data type and provided an example. When I transpiled it on my computer, it produced an error showing that an integer cannot be assigned to a variable declared as a string. What I did was to declare the variable 'message' without the string data type. In that case it will act as a dynamically declared variable capable of accepting values of any data type. When I transpiled again and ran node.js on it, it worked! Please kindly make the correction. 

Again, on the example that shows that a variable's data type can be derived from other variables, I think the data type, number, declared for the variable 'sum' should be omitted. That way its data type can effectively be derived form those of variable 'i' and 'j'.  
![variable](https://user-images.githubusercontent.com/67865771/86535668-d6d9cc80-bed9-11ea-9607-f021bb99c2a3.PNG),
![variable-derive-datatype](https://user-images.githubusercontent.com/67865771/86535678-ea853300-bed9-11ea-812a-620e084c3cb5.PNG)

**Comment by cosmiclearn** [comment]
Thank you for visiting CosmicLearn and your valuable feedback.
I have fixed the two issues you reported. 
https://www.cosmiclearn.com/typescript/variables.php

Sorry for the delay, been a stressful time due to covid and other projects! Keep cosmiclearning.
